apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: mellgitson/todo-api:1ba421369fbb9abc7b5610696fc3f823d6067f86
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
